"""api_key_rate_limit_redesign

Revision ID: 99540139637b
Revises: fb6ea2a0b401
Create Date: 2026-05-16 15:35:42.724526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '99540139637b'
down_revision: Union[str, None] = '2426e9fb22ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_PERIOD_OLD = sa.Enum('MINUTE', 'HOUR', 'DAY', name='period')
_PERIOD_NEW = sa.Enum('MINUTE', 'HOUR', 'DAY', 'MONTH', name='period')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. ApiKey.id: VARCHAR → UUID (fixes type inconsistency with user.id)
    op.alter_column('auth_api_key', 'id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Uuid(),
               existing_nullable=False)

    # 2. RateLimit: add api_key_id (primary enforcement axis)
    op.add_column('auth_rate_limit', sa.Column('api_key_id', sa.Uuid(), nullable=True))

    # 3. RateLimit: make user_id nullable (becomes fallback default, not owner)
    op.alter_column('auth_rate_limit', 'user_id',
               existing_type=mysql.CHAR(length=32),
               nullable=True)

    # 4. RateLimit: extend period enum with MONTH
    op.alter_column('auth_rate_limit', 'period',
               existing_type=_PERIOD_OLD,
               type_=_PERIOD_NEW,
               existing_nullable=False)

    # 5. RateLimit: indexes and constraints
    op.create_index(op.f('ix_auth_rate_limit_api_key_id'), 'auth_rate_limit', ['api_key_id'], unique=False)
    op.create_unique_constraint('uq_ratelimit_api_key_period', 'auth_rate_limit', ['api_key_id', 'period'])
    op.create_unique_constraint('uq_ratelimit_user_period', 'auth_rate_limit', ['user_id', 'period'])

    # Note: ck_ratelimit_has_owner CHECK constraint is defined in the model
    # __table_args__ and applied on fresh table creation. MariaDB InnoDB does
    # not support adding CHECK via ALTER TABLE in non-transactional DDL mode,
    # so it is omitted here and enforced at the application layer.

    # 6. FK: api_key_id → auth_api_key.id (named for safe downgrade)
    op.create_foreign_key(
        'fk_ratelimit_api_key_id',
        'auth_rate_limit', 'auth_api_key',
        ['api_key_id'], ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ratelimit_api_key_id', 'auth_rate_limit', type_='foreignkey')
    op.drop_constraint('uq_ratelimit_user_period', 'auth_rate_limit', type_='unique')
    op.drop_constraint('uq_ratelimit_api_key_period', 'auth_rate_limit', type_='unique')
    op.drop_index(op.f('ix_auth_rate_limit_api_key_id'), table_name='auth_rate_limit')

    op.alter_column('auth_rate_limit', 'period',
               existing_type=_PERIOD_NEW,
               type_=_PERIOD_OLD,
               existing_nullable=False)
    op.alter_column('auth_rate_limit', 'user_id',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    op.drop_column('auth_rate_limit', 'api_key_id')

    op.alter_column('auth_api_key', 'id',
               existing_type=sa.Uuid(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
