codecov:
    require_ci_to_pass: true

ignore:
    - "examples/*"
    - "examples/imgtools_web.py"
    - "examples/imgtools_perf.py"
    - "examples/multiprocess.py"
    - "setup.py"
    - "imgtools_m8/__init__.py"
