"""Initial m8 migration

Revision ID: 3a7ac9337a43
Revises:
Create Date: 2026-05-14 15:52:05.841816

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3a7ac9337a43"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dcnt_category",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
        sa.UniqueConstraint("slug", name="uq_category_slug"),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_dcnt_category_id"), "dcnt_category", ["id"], unique=False)
    op.create_index(
        op.f("ix_dcnt_category_owner_id"), "dcnt_category", ["owner_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dcnt_category_owner_id"), table_name="dcnt_category")
    op.drop_index(op.f("ix_dcnt_category_id"), table_name="dcnt_category")
    op.drop_table("dcnt_category")
    # ### end Alembic commands ###
