"""Initial auth migration

Revision ID: 2426e9fb22ef
Revises: 
Create Date: 2026-05-14 15:54:00.636951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2426e9fb22ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('provider', sa.Enum('PASSWORD', 'GOOGLE', name='authprovidertype'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('SUPERADMIN', 'ADMIN', 'WRITER', 'READER', 'USER', name='roletype'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('oauth_user_id', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('telegram_id', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_user_id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index(op.f('ix_auth_user_email'), 'auth_user', ['email'], unique=True)
    op.create_index(op.f('ix_auth_user_id'), 'auth_user', ['id'], unique=False)
    op.create_table('auth_api_key',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_auth_api_key_id'), 'auth_api_key', ['id'], unique=False)
    op.create_index(op.f('ix_auth_api_key_user_id'), 'auth_api_key', ['user_id'], unique=False)
    op.create_table('auth_client_session',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('provider', sa.Enum('PASSWORD', 'GOOGLE', name='authprovidertype'), nullable=False),
    sa.Column('jwt_jti', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('refresh_token_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('jwt_expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('external_access_token', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('external_refresh_token', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('external_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_client_session_id'), 'auth_client_session', ['id'], unique=False)
    op.create_index(op.f('ix_auth_client_session_user_id'), 'auth_client_session', ['user_id'], unique=False)
    op.create_table('auth_rate_limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.Enum('MINUTE', 'HOUR', 'DAY', name='period'), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_rate_limit_user_id'), 'auth_rate_limit', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_rate_limit_user_id'), table_name='auth_rate_limit')
    op.drop_table('auth_rate_limit')
    op.drop_index(op.f('ix_auth_client_session_user_id'), table_name='auth_client_session')
    op.drop_index(op.f('ix_auth_client_session_id'), table_name='auth_client_session')
    op.drop_table('auth_client_session')
    op.drop_index(op.f('ix_auth_api_key_user_id'), table_name='auth_api_key')
    op.drop_index(op.f('ix_auth_api_key_id'), table_name='auth_api_key')
    op.drop_table('auth_api_key')
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_email'), table_name='auth_user')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
